# Generated by Django 3.0.8 on 2021-06-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mita', '0003_emailentry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='Bio',
            field=models.TextField(blank=True),
        ),
    ]
